### ISSUE TITLE
Only listens on localhost

### ISSUE THREAD

**Issue by Trekgater** [primetime43/GAPS-2#3]
I run / ran GAPS as a service (using NSSM) on the Plex server and accessed it from my normal pc.

With GAPS2 it only listens on 127.0.0.1 so is inaccessible from another machine

**Comment by primetime43** [comment]
> I run / ran GAPS as a service (using NSSM) on the Plex server and accessed it from my normal pc.
> 
> With GAPS2 it only listens on 127.0.0.1 so is inaccessible from another machine

Okay, so you want to be able to access it on your local network from another device/machine?

**Comment by primetime43** [comment]
Issue fixed in v1.0.2
