### ISSUE TITLE
Cannot link Plex Account

### ISSUE THREAD

**Issue by Trekgater** [primetime43/GAPS-2#4]
If I run GAPS2 on the main server where it needs to be then it will not sign in or show any pages to sign in

Clicking Link Plex Account just shows 
Loading Data under the Servers

Running on Windows Server 2016 

If I run the exe file a UNC path from my normal pc.

It will load PlexAPI (https://app.plex.tv/) and gives a button to sign in, after clicking the sign in button a dialogue box shows 
127.0.0.1:5000 says
Could not log into Plex account 

After a few tries it will show the plex data but doesn't seem to save the config as it's lost after closing and opening

Running on Windows 11

Copying it to local drive or running as admin makes no difference.

**Comment by primetime43** [comment]
> If I run GAPS2 on the main server where it needs to be then it will not sign in or show any pages to sign in
> 
> Clicking Link Plex Account just shows Loading Data under the Servers
> 
> Running on Windows Server 2016
> 
> If I run the exe file a UNC path from my normal pc.
> 
> It will load PlexAPI (https://app.plex.tv/) and gives a button to sign in, after clicking the sign in button a dialogue box shows 127.0.0.1:5000 says Could not log into Plex account
> 
> After a few tries it will show the plex data but doesn't seem to save the config as it's lost after closing and opening
> 
> Running on Windows 11
> 
> Copying it to local drive or running as admin makes no difference.

hmm okay, could you show what the console log is showing possibly? Any errors in there etc.

**Comment by Trekgater** [comment]
127.0.0.1 - - [04/Jul/2023 19:18:47] "GET /get_active_server HTTP/1.1" 200 -
127.0.0.1 - - [04/Jul/2023 19:19:39] "POST /link_plex_account HTTP/1.1" 200 -
127.0.0.1 - - [04/Jul/2023 19:19:58] "POST /save_plex_data HTTP/1.1" 200 -
127.0.0.1 - - [04/Jul/2023 19:20:07] "GET /get_active_server HTTP/1.1" 200 -

![GAPS2](https://github.com/primetime43/GAPS-2/assets/85680684/a117c917-6864-4d0c-898f-1ac5e9e4512b)

**Comment by primetime43** [comment]
Issue fixed in v1.0.2
